/**
 * The one place a format slug can come from.
 *
 * Before 2026-09-20 there were four: VENTURE_FORMATS, LANES, FACTORY_CHANNELS
 * and PUBLIC_SERIES, each with its own copy of the labels, and a fifth in
 * FORMAT_ADAPTS restating the mandates in prose. The publication renamed its
 * formats on 2026-09-17 and three days later all four still offered the retired
 * names, because a rename in four places is a rename that has to be remembered
 * four times and never is. This file is the answer, and it follows the
 * precedent ventureOptions.ts already set for venture names.
 *
 * The data is `formats.generated.json`, a snapshot of `public.venture_formats`
 * and `public.format_aliases` in Mindmaker OS, regenerated by
 * `scripts/sync-formats.mts`. It is a snapshot rather than a live read because
 * these are build-time constants and a module that cannot boot without the
 * network is a module that cannot be tested. `scripts/check-format-drift.mts`
 * reads the live table in CI and fails when the two disagree, which is what
 * keeps the snapshot from becoming a fifth copy.
 *
 * WHAT IS NOT HERE, on purpose: the mandate prose. `venture_formats.mandate`
 * holds each mandate in full and a copy in a repo file drifts while the table
 * does not. Anything that needs the mandate reads it at run time.
 */
import generated from './formats.generated.json'

export type FormatKind = 'subchannel' | 'holding' | 'any' | 'retired'

export interface FormatDef {
  slug: string
  label: string
  /** "Mondays", "Wednesdays", "Fridays". The table's own wording. */
  cadence_label: string
  /** 1 for a weekly slot, 0.5 for the standing one, 0 for anything not commissioned. */
  target_per_week: number
  hero: boolean
  gear: string | null
  sort_order: number
  kind: FormatKind
}

export interface FormatAlias { alias: string; slug: string; retired_on: string }

export const FORMATS: readonly FormatDef[] = Object.freeze(
  (generated.formats as FormatDef[]).map(f => Object.freeze(f)),
)
export const FORMAT_ALIASES: readonly FormatAlias[] = Object.freeze(
  (generated.aliases as FormatAlias[]).map(a => Object.freeze(a)),
)
export const FORMATS_READ_AT = generated.read_at

const BY_SLUG = new Map(FORMATS.map(f => [f.slug, f]))
const ALIAS_TO_SLUG = new Map(FORMAT_ALIASES.map(a => [a.alias, a.slug]))

/** The three commissioned subchannels, in the table's own order. */
export const SUBCHANNELS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'subchannel'),
)

/** Subchannels plus the holding lane: everything a live row may legitimately carry. */
export const WRITABLE_FORMATS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'subchannel' || f.kind === 'holding'),
)

export const RETIRED_FORMATS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'retired'),
)

/**
 * Resolve anything that might be a format to a live slug.
 *
 * Returns null rather than guessing, because the six foreign keys to
 * venture_formats(slug) exist precisely so an unknown value fails the write
 * instead of degrading, and a resolver that invents a fallback would put the
 * degrading back. The caller decides what an unresolvable value means, and the
 * failure vocabulary has a reason for it: `format_not_in_venture_formats`.
 */
export function resolveFormat(value?: string | null): FormatDef | null {
  if (!value) return null
  const v = String(value).trim()
  // THE ALIAS LEDGER IS READ FIRST, and the order is the whole point.
  //
  // `money_of_ai` and `built_with_ai` are each two rows: a retired row in
  // venture_formats (what the format WAS) and an alias row in format_aliases
  // (what the name MEANS NOW). Reading venture_formats first made every
  // historical `lane_slot = 'built_with_ai'` resolve to a retired format, whose
  // kind is not `subchannel`, so the rooms dropped it and the idea disappeared
  // from the dashboard rather than appearing under under.the.hood. That is the
  // exact failure the ledger exists to prevent, so the ledger wins.
  //
  // Nothing loses the retired rows by this: RETIRED_FORMATS reads FORMATS
  // directly, and formatSpelling() below is how a writer refuses a retired
  // spelling without a resolver that pretends not to understand it.
  const viaAlias = ALIAS_TO_SLUG.get(v)
  if (viaAlias) return BY_SLUG.get(viaAlias) ?? null
  const direct = BY_SLUG.get(v)
  if (direct) return direct
  // Labels are matched last and case-insensitively, so "The Money of AI" and
  // "follow.the.money" both land somewhere, but a near miss still fails.
  const lower = v.toLowerCase()
  const byLabel = FORMATS.find(f => f.label.toLowerCase() === lower)
  if (!byLabel) return null
  // A retired label resolves the same way its slug does, or the read side would
  // route "Built with AI" and `built_with_ai` to two different places.
  return byLabel.kind === 'retired' ? resolveFormat(byLabel.slug) : byLabel
}

export type FormatSpelling = 'current' | 'retired' | 'unknown'

/**
 * Whether this exact string may be written to a new row.
 *
 * `resolveFormat` answers "what does this mean", which is a read-side question
 * and must be generous: an eight-month-old row saying `built_with_ai` is a
 * under.the.hood piece. This answers "is this how we spell it today", which is a
 * write-side question and must not be: `built_with_ai` is a retired spelling
 * even though it resolves cleanly, and writing it again would start the drift
 * over. The two questions were one function until 2026-09-20 and the single
 * answer was wrong for one of them whichever way it was ordered.
 */
export function formatSpelling(value?: string | null): FormatSpelling {
  if (!value) return 'unknown'
  const v = String(value).trim()
  if (ALIAS_TO_SLUG.has(v)) return 'retired'
  const direct = BY_SLUG.get(v)
  if (direct) return direct.kind === 'retired' ? 'retired' : 'current'
  return resolveFormat(v) ? 'retired' : 'unknown'
}

/** The one line under a room header: what this subchannel is for, in a reader's
 *  words.
 *
 *  It lives here rather than in the room component because on 2026-09-20 it did
 *  not, and the Content tab crashed on the desk with "Cannot read properties of
 *  undefined (reading 'question')". LaneRoom keyed its copy on the two retired
 *  slugs; widening RoomId from a union to `string` removed the exhaustiveness
 *  check that had been the only thing keeping that map complete, so the third
 *  format reached a lookup that had no entry for it. tsc cannot see it either,
 *  because a `Record<string, T>` index returns T rather than T | undefined
 *  without noUncheckedIndexedAccess.
 *
 *  So the lookup returns null rather than throwing, the caller renders nothing
 *  rather than crashing, and scripts/check-content-taxonomy.mts fails the build
 *  when a subchannel has no line. A gap takes down CI, never the app. */
const STANDING_QUESTION: Readonly<Record<string, string>> = Object.freeze({
  follow_the_money: 'Stories about where the money moves in AI, and who ends up better or worse off.',
  mind_the_gap: 'Stories that notice a pattern across several threads, and say what it means is coming.',
  under_the_hood: 'Stories that take a build apart to show what goes together, and why this one worked.',
})

/** The reader-facing line for a format, or null when none is written yet. */
export function standingQuestion(value?: string | null): string | null {
  const f = resolveFormat(value)
  return (f && STANDING_QUESTION[f.slug]) || null
}

/** Subchannels with no standing question. Empty in a healthy tree; the taxonomy
 *  guard fails the build on anything else. */
export function subchannelsMissingAStandingQuestion(): string[] {
  return SUBCHANNELS.filter(f => !STANDING_QUESTION[f.slug]).map(f => f.slug)
}

/** The label to show a person. Never a title-cased slug. */
export function formatLabel(value?: string | null): string {
  return resolveFormat(value)?.label ?? 'unknown format'
}

/** True when the value names a format that may be commissioned today, under any
 *  of its spellings. Ask `formatSpelling(value) === 'current'` as well before
 *  storing the string itself. */
export function isLiveFormat(value?: string | null): boolean {
  const f = resolveFormat(value)
  return !!f && (f.kind === 'subchannel' || f.kind === 'holding')
}

/** Why a value could not be used, in one sentence, for a refusal that says so. */
export function whyNotAFormat(value?: string | null): string {
  if (!value) return 'No format was given, and the machine does not pick one for you.'
  const f = resolveFormat(value)
  if (!f) {
    return `"${value}" is not a format venture_formats has, so there is no mandate to write against and no slug to store. The live ones are ${SUBCHANNELS.map(s => s.slug).join(', ')}.`
  }
  if (formatSpelling(value) === 'retired') {
    const was = BY_SLUG.get(String(value).trim())
    const when = was?.cadence_label.replace('retired ', '') ?? FORMAT_ALIASES.find(a => a.alias === String(value).trim())?.retired_on ?? 'an earlier rename'
    return `"${value}" is a retired spelling, dropped on ${when}. It reads as ${f.slug} for historical rows and must never be written to a new one.`
  }
  if (f.kind === 'any') return `"${value}" means "either", which is a query, not a destination.`
  return ''
}
