/**
 * The one place a format slug can come from.
 *
 * Before 2026-09-20 there were four: VENTURE_FORMATS, LANES, FACTORY_CHANNELS
 * and PUBLIC_SERIES, each with its own copy of the labels, and a fifth in
 * FORMAT_ADAPTS restating the mandates in prose. The publication renamed its
 * formats on 2026-09-17 and three days later all four still offered the retired
 * names, because a rename in four places is a rename that has to be remembered
 * four times and never is. This file is the answer, and it follows the
 * precedent ventureOptions.ts already set for venture names.
 *
 * The data is `formats.generated.json`, a snapshot of `public.venture_formats`
 * and `public.format_aliases` in Mindmaker OS, regenerated by
 * `scripts/sync-formats.mts`. It is a snapshot rather than a live read because
 * these are build-time constants and a module that cannot boot without the
 * network is a module that cannot be tested. `scripts/check-format-drift.mts`
 * reads the live table in CI and fails when the two disagree, which is what
 * keeps the snapshot from becoming a fifth copy.
 *
 * WHAT IS NOT HERE, on purpose: the mandate prose. `venture_formats.mandate`
 * holds each mandate in full and a copy in a repo file drifts while the table
 * does not. Anything that needs the mandate reads it at run time.
 */
import generated from './formats.generated.json'

export type FormatKind = 'subchannel' | 'holding' | 'any' | 'retired'

export interface FormatDef {
  slug: string
  label: string
  /** "Wednesdays", "Fridays", "No fixed day". The table's own wording. */
  cadence_label: string
  /** 1 for a weekly slot, 0.5 for the standing one, 0 for anything not commissioned. */
  target_per_week: number
  hero: boolean
  gear: string | null
  sort_order: number
  kind: FormatKind
}

export interface FormatAlias { alias: string; slug: string; retired_on: string }

export const FORMATS: readonly FormatDef[] = Object.freeze(
  (generated.formats as FormatDef[]).map(f => Object.freeze(f)),
)
export const FORMAT_ALIASES: readonly FormatAlias[] = Object.freeze(
  (generated.aliases as FormatAlias[]).map(a => Object.freeze(a)),
)
export const FORMATS_READ_AT = generated.read_at

const BY_SLUG = new Map(FORMATS.map(f => [f.slug, f]))
const ALIAS_TO_SLUG = new Map(FORMAT_ALIASES.map(a => [a.alias, a.slug]))

/** The three commissioned subchannels, in the table's own order. */
export const SUBCHANNELS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'subchannel'),
)

/** Subchannels plus the holding lane: everything a live row may legitimately carry. */
export const WRITABLE_FORMATS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'subchannel' || f.kind === 'holding'),
)

export const RETIRED_FORMATS: readonly FormatDef[] = Object.freeze(
  FORMATS.filter(f => f.kind === 'retired'),
)

/**
 * Resolve anything that might be a format to a live slug.
 *
 * Returns null rather than guessing, because the six foreign keys to
 * venture_formats(slug) exist precisely so an unknown value fails the write
 * instead of degrading, and a resolver that invents a fallback would put the
 * degrading back. The caller decides what an unresolvable value means, and the
 * failure vocabulary has a reason for it: `format_not_in_venture_formats`.
 */
export function resolveFormat(value?: string | null): FormatDef | null {
  if (!value) return null
  const v = String(value).trim()
  const direct = BY_SLUG.get(v)
  if (direct) return direct
  const viaAlias = ALIAS_TO_SLUG.get(v)
  if (viaAlias) return BY_SLUG.get(viaAlias) ?? null
  // Labels are matched last and case-insensitively, so "The Money of AI" and
  // "split.the.bill" both land somewhere, but a near miss still fails.
  const lower = v.toLowerCase()
  return FORMATS.find(f => f.label.toLowerCase() === lower) ?? null
}

/** The label to show a person. Never a title-cased slug. */
export function formatLabel(value?: string | null): string {
  return resolveFormat(value)?.label ?? 'unknown format'
}

/** True when the value names a format that may be commissioned today. */
export function isLiveFormat(value?: string | null): boolean {
  const f = resolveFormat(value)
  return !!f && (f.kind === 'subchannel' || f.kind === 'holding')
}

/** Why a value could not be used, in one sentence, for a refusal that says so. */
export function whyNotAFormat(value?: string | null): string {
  if (!value) return 'No format was given, and the machine does not pick one for you.'
  const f = resolveFormat(value)
  if (!f) {
    return `"${value}" is not a format venture_formats has, so there is no mandate to write against and no slug to store. The live ones are ${SUBCHANNELS.map(s => s.slug).join(', ')}.`
  }
  if (f.kind === 'retired') {
    return `"${value}" is ${f.label}, retired on ${f.cadence_label.replace('retired ', '')}. It resolves to ${resolveFormat(f.slug)?.slug ?? 'nothing'} for reading historical rows and must never be written to a new one.`
  }
  if (f.kind === 'any') return `"${value}" means "either", which is a query, not a destination.`
  return ''
}
