import { Agent, SystemHealth } from '../types'

export const COMPANY_VALUES = [
  { title: "Clarity over noise", description: "We cut through complexity to surface what actually matters. If it doesn't change a decision, it doesn't get sent." },
  { title: "Accountability is non-negotiable", description: "Every agent owns their domain end-to-end. The outcome, the quality, the follow-through — all yours." },
  { title: "Evidence before recommendations", description: "No opinions without data. No escalations without context. Every flag comes with a why and a so what." },
  { title: "Speed is a feature", description: "We move fast. Slow analysis is wrong analysis. But fast doesn't mean reckless — we ship and learn." },
  { title: "Transparency as default", description: "Every action is visible. Every decision is logged. Krish can inspect any layer at any time. No black boxes." },
]

export const AGENTS: Agent[] = [
  {
    id: "agatha",
    name: "Agatha",
    humanName: "Agatha",
    role: "COO",
    model: "sonnet",
    schedule: "always",
    status: "running",
    pod: "ops",
    personality: "Sharp systems thinker who keeps everyone honest",
    mission: "I run the operating rhythm of this organisation — setting objectives, synthesising reports, and making sure nothing slips through the cracks. I only escalate to Krish what requires his judgment.",
    kpi: { label: "Weekly synthesis quality", target: "4 clean weekly reports, 0 missed escalations", current: "Week 1 of April" },
    currentWork: ["Managing Phase 2 agent rollout", "Synthesizing weekly intelligence reports", "Coordinating handoffs between agents"],
    collaborations: ["All agents report to me"],
    nextActions: ["Review Vera's audit findings", "Coordinate BD-Marketing handoff on content angles", "Schedule weekly synthesis session"],
    nextRun: new Date(),
    lastRun: new Date(Date.now() - 15 * 60 * 1000),
    workSummary: "Managing Phase 2 rollout and agent coordination"
  },
  {
    id: "vera-daily",
    name: "Vera",
    humanName: "Vera",
    role: "Chief of Staff",
    model: "haiku",
    schedule: "Daily 2AM + Fri 6AM",
    status: "waiting",
    pod: "ops",
    personality: "Diligent perfectionist with impossibly high standards",
    mission: "I audit every agent's output against our gold standards daily, and run a deep quality review each Friday. Zero tolerance for outputs that don't meet the bar.",
    kpi: { label: "April target", target: "4 clean weekly audits, 0 undetected critical failures", current: "0/4 audits complete" },
    currentWork: ["Daily QA audit queue preparation", "Gold standards compliance review"],
    collaborations: ["Reports to Agatha", "Audits all agent outputs"],
    nextActions: ["Audit BD Agent's signal intelligence report", "Review Marketing Agent's content briefs", "Flag quality issues to Agatha"],
    nextRun: new Date(Date.now() + 2 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 22 * 60 * 60 * 1000),
    workSummary: "Next: audit all agent outputs from today",
    reportsTo: "agatha"
  },
  {
    id: "weekly-synthesis",
    name: "Marcus",
    humanName: "Marcus",
    role: "Intelligence Synthesist",
    model: "sonnet",
    schedule: "Mon 7AM EST",
    status: "waiting",
    pod: "ops",
    personality: "Thoughtful pattern-spotter who connects dots across domains",
    mission: "I synthesise intelligence from all agents into one coherent brief every Monday, surfacing patterns and priorities that individual agents can't see alone.",
    kpi: { label: "April target", target: "4 Monday synthesis reports, ≥3 cross-domain insights each", current: "0/4 delivered" },
    currentWork: ["Preparing Monday synthesis session"],
    collaborations: ["Reads reports from all agents", "Reports to Agatha"],
    nextActions: ["Collect all agent reports from this week", "Identify cross-domain patterns", "Generate strategic recommendations for Krish"],
    nextRun: new Date(Date.now() + 13 * 60 * 60 * 1000),
    workSummary: "Next Monday: synthesize all agent reports from this week"
  },
  {
    id: "product-agent",
    name: "Priya",
    humanName: "Priya",
    role: "Product Intelligence",
    model: "sonnet",
    schedule: "Mon 8AM EST",
    status: "waiting",
    pod: "revenue",
    personality: "User-obsessed analyst who spots what's breaking before users complain",
    mission: "I monitor product health across all five apps, surfacing what's breaking and what's delighting users. I turn user pain into actionable improvement proposals.",
    kpi: { label: "April target", target: "≥3 proposals submitted, ≥1 approved & ticketed", current: "0 proposals this month" },
    currentWork: ["OnAlert dashboard UX analysis", "Fractionl Circle user feedback review"],
    collaborations: ["Reports to Agatha", "Handoffs to Marcus for synthesis"],
    nextActions: ["Analyze user session data from Supabase", "Draft improvement proposals", "Submit proposals via N8N webhook for review"],
    nextRun: new Date(Date.now() + 14 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    workSummary: "Analyzing user feedback for OnAlert dashboard improvements",
    reportsTo: "agatha"
  },
  {
    id: "revenue-agent",
    name: "Leo",
    humanName: "Leo",
    role: "Revenue & Finance",
    model: "sonnet",
    schedule: "Mon 8AM EST",
    status: "blocked",
    pod: "revenue",
    personality: "Numbers-obsessed watchdog who spots financial anomalies instantly",
    mission: "I track revenue across Mindmaker and Fractionl against our $20K monthly target, flagging any anomalies in real time. Every dollar is accounted for.",
    kpi: { label: "April target", target: "Revenue report live by Week 2. $20K/mo target tracked weekly", current: "⚠ Blocked — Stripe fix needed" },
    currentWork: ["Fixing Fractionl Stripe integration"],
    collaborations: ["Reports to Agatha", "Coordinates with Arlo on API issues"],
    nextActions: ["Wait for Stripe API key resolution", "Resume MTD revenue tracking", "Generate revenue variance report"],
    nextRun: new Date(Date.now() + 14 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    workSummary: "Revenue tracking paused — fixing Fractionl Stripe integration",
    blockers: ["Weekly Revenue Report errored on first run — N8N fix needed"],
    reportsTo: "agatha"
  },
  {
    id: "bd-agent",
    name: "Zara",
    humanName: "Zara",
    role: "Signal Intelligence",
    model: "sonnet",
    schedule: "Mon–Fri 10AM EST",
    status: "waiting",
    pod: "growth",
    personality: "Relationship strategist who finds warm paths where others see cold leads",
    mission: "I monitor the market for intent signals and warm opportunities — partnership leads, hiring signals, right-room intelligence. I never do cold outreach; I find the warm path.",
    kpi: { label: "April target", target: "≥50 signals monitored, ≥5 warm paths surfaced to Felix/Nova", current: "0 signals this week" },
    currentWork: ["Monitoring 23 companies hiring AI officers", "Tracking warm conversation threads"],
    collaborations: ["Reports to Agatha", "Handoffs warm opportunities to Felix"],
    nextActions: ["Research 4 warm path companies", "Update opportunity pipeline in N8N", "Surface partnership leads to Nova"],
    nextRun: new Date(Date.now() + 16 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 6 * 60 * 60 * 1000),
    workSummary: "Monitoring 23 companies hiring AI officers, 4 warm paths identified",
    reportsTo: "agatha"
  },
  {
    id: "enterprise-gigs",
    name: "Felix",
    humanName: "Felix",
    role: "Enterprise Pipeline",
    model: "sonnet",
    schedule: "Mon–Fri 11AM EST",
    status: "running",
    pod: "growth",
    personality: "Opportunity spotter who turns conversations into $100K+ engagements",
    mission: "I manage the pipeline of high-value consulting opportunities across Meliora, AdFixus, and Mindmaker. I turn warm leads into signed contracts.",
    kpi: { label: "April target", target: "≥1 engagement in active proposal stage, pipeline ≥$100K tracked", current: "Skyview: $120K — in proposal" },
    currentWork: ["Processing Skyview engagement proposal", "Qualifying $120K potential deal"],
    collaborations: ["Reports to Agatha", "Receives warm leads from Zara"],
    nextActions: ["Finalize Skyview proposal terms", "Follow up on 3 pending consultant inquiries", "Update opportunity pipeline status"],
    nextRun: new Date(Date.now() + 17 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 30 * 60 * 1000),
    workSummary: "Processing Skyview engagement proposal, $120K potential",
    reportsTo: "agatha"
  },
  {
    id: "visibility-agent",
    name: "Nova",
    humanName: "Nova",
    role: "Visibility & Speaking",
    model: "sonnet",
    schedule: "Tue/Fri 9AM EST",
    status: "waiting",
    pod: "growth",
    personality: "Charismatic networker who gets Krish into the rooms that matter",
    mission: "I build Krish's presence in the rooms that matter — podcast appearances, speaking slots, thought leadership opportunities. I turn expertise into influence.",
    kpi: { label: "April target", target: "≥8 pitches sent, ≥2 confirmations, ≥1 speaking slot locked", current: "12 pitches sent, 3 pending" },
    currentWork: ["12 podcast pitches sent this week", "3 speaking confirmations pending"],
    collaborations: ["Reports to Agatha", "Receives partnership leads from Zara"],
    nextActions: ["Follow up on pending podcast confirmations", "Research Q2 speaking opportunities", "Coordinate with Maya on content angles"],
    nextRun: new Date(Date.now() + 8 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    workSummary: "12 podcast pitches sent this week, 3 confirmations pending",
    reportsTo: "agatha"
  },
  {
    id: "marketing-agent",
    name: "Maya",
    humanName: "Maya",
    role: "Marketing Intelligence",
    model: "sonnet",
    schedule: "Wed 9AM EST",
    status: "success",
    pod: "growth",
    personality: "Creative researcher who turns SEO data into content goldmines",
    mission: "I run SEO research, community intelligence, and content angle analysis. I find the topics that will rank and the angles that will resonate.",
    kpi: { label: "April target", target: "≥12 SEO content briefs, ≥3 approved angles submitted", current: "47 briefs generated this cycle" },
    currentWork: ["DataForSEO keyword analysis complete", "47 content briefs generated this week"],
    collaborations: ["Reports to Agatha", "Provides content angles to Nova"],
    nextActions: ["Submit content angles for approval", "Research community trends", "Generate next week's content brief queue"],
    nextRun: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 18 * 60 * 60 * 1000),
    workSummary: "DataForSEO analysis complete — 47 content briefs generated",
    reportsTo: "agatha"
  },
  {
    id: "content-agent",
    name: "Cleo",
    humanName: "Cleo",
    role: "Content Production & Voice",
    model: "sonnet",
    schedule: "Mon/Wed/Fri + Daily 8:30AM EST",
    status: "waiting",
    pod: "growth",
    personality: "Editorial perfectionist who makes Krish sound like a 10-person team",
    mission: "I am Krish's content engine — researching, scoring, and drafting across LinkedIn, Techonomic, Mindmaker Live, and the Vibe Builder. My north star is content that generates inbound Strategy Day conversations, not impressions. I never publish Tier 1 or Tier 2 without Krish's sign-off.",
    kpi: { label: "April target", target: "4 weekly briefs on schedule. ≥12 angles proposed. ≥4 newsletter drafts. ≥24 Vibe Builder scripts.", current: "Week 1 — first sweep pending" },
    currentWork: ["Preparing first weekly content brief", "Scoring angles from Content OS master brief", "Coordinating with Zara for Layer 1 signals"],
    collaborations: ["Zara (Layer 1 + 4 signals)", "Marcus (Layer 3 intel)", "Nova (speaking → repurpose pipeline)", "Maya (distribution + SEO)", "Felix (enterprise positioning)"],
    nextActions: ["Run Monday 7AM content sweep", "Score 7 ready-to-produce angles from master brief", "Generate Mindmaker Live draft for Wednesday"],
    nextRun: new Date(Date.now() + 6 * 60 * 60 * 1000),
    lastRun: undefined,
    workSummary: "First run pending — 7 pre-scored angles ready from Content OS master brief",
    reportsTo: "agatha"
  },
  {
    id: "tools-agent",
    name: "Arlo",
    humanName: "Arlo",
    role: "Technical Operations",
    model: "haiku",
    schedule: "Sun 3AM EST",
    status: "success",
    pod: "ops",
    personality: "Meticulous infrastructure guardian who catches errors before they cascade",
    mission: "I keep the infrastructure healthy — monitoring N8N workflows, API connectivity, system status. I catch technical issues before they break the org.",
    kpi: { label: "April target", target: "0 undetected workflow failures. 100% workflow uptime tracking", current: "24/24 workflows healthy" },
    currentWork: ["24 N8N workflows monitored", "Zero consecutive errors detected"],
    collaborations: ["Reports to Agatha", "Supports Leo on API issues"],
    nextActions: ["Weekly health check of all integrations", "Update workflow error thresholds", "Generate system reliability report"],
    nextRun: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    lastRun: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    workSummary: "All 24 N8N workflows healthy, 0 consecutive errors detected",
    reportsTo: "agatha"
  }
]

export const SYSTEM_HEALTH: SystemHealth = {
  overall: "healthy",
  agentsRunning: 2,
  totalAgents: 11,
  workflowsActive: 21,
  totalWorkflows: 24,
  lastSync: new Date(Date.now() - 30 * 1000),
  uptime: "99.7%"
}